version: '3.8'
services:
  nextjs_app:
    container_name: 'nextjs_app'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=deploy
      - NEXT_PUBLIC_LMS_URL=http://152.42.220.220:3000
      - NEXT_PUBLIC_ISTAD_LMS_API_URL=http://152.42.220.220:7777/api/v1
      - ISTAD_LMS_API_URL=http://152.42.220.220:7777/api/v1
      - COOKIE_REFRESH_TOKEN_NAME=refresh-istad-lms
