version: '3.8'
services:
  nextjs_app:
    container_name: 'nextjs_app'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
